[pytest]
addopts = 
    -v
    --headless=true 
    --browser chromium
    --browser chromium 
    --browser firefox 
    --browser webkit 
    -n auto 
    
    
    --alluredir=reports/allure-results